### ISSUE TITLE
BUILD: create needed folder structure

### ISSUE THREAD

**Issue by EMCain** [EMCain/unity-demo#1]
The folder structure we want looks something like this: 

- root folder 
  - Builds
    -  GameName-1.0.0
      -  Zips

(Creating a zipped folder out of that and placing it in the zips folder will come later) 

Steps needed 

- [ ] Create  `root folder/Builds` if it does not exist
- [ ] Generate a file name 
- [ ] Handle the case where there is an existing file or folder named that (see questions below) 
- [ ] Create the new folder for that file name 
- [ ] Create a Zips subfolder within the empty folder. 
- [ ] Create a zip of that (currently empty) folder in the Zips folder (note: can wait til #4 if wanted) 

Questions to figure out here: 

* does the above folder structure and file naming convention look ok? 
* what do we want to happen if there already exists a file at `root folder/Builds/Zips/GameName-x.x.x.exe` and/or a folder at `root folder/Builds/GameName-x.x.x`? 
- Overwrite the folder?
- Create a new folder called GameName-x.x.x (1) or whatever? 
- whichever we choose - should the command line application ask for confirmation ("are you sure you want to overwrite ___? y/n") or just go ahead?
- if it does ask for confirmation should there be a -f option to override that?

**Comment by EMCain** [comment]
Notes from conversation with @jacobliv 

* I'd say we want to be intentional with the versions, so if it exists, fail the build, and log that it exists and maybe a path to the version file to update or something
* need only a major and minor version, so 1.1 or whatever. It will be 0.x until we have the version we are ready to release and submit to the game jam, which will be 1.0.

**Comment by jacobliv** [comment]
> * root folder
>   * Builds  
>     * GameName-1.0.0
>     * Zips

Lets add onto this a bit. 
I love the idea of having a builds folder, and then generating subfolders for each version. 
Inside of those folders, we should probably have this structure: 
* root folder
  * Builds  
    * GameName-1.0.0
      * GameName-Mac-1.0.0
      * GameName-Windows-1.0.0
      * GameName-Web-1.0.0
      * Zips
        * GameName-Mac-1.0.0.zip
        * GameName-Windows-1.0.0.zip
        * GameName-Web-1.0.0.zip
    
> * does the above folder structure and file naming convention look ok?
- Close, but I moved the zip folder down a level to each game version, otherwise we will have a zip folder with every version of the game. Granted, it wont be a shit ton, it would be good to keep that simple and clear.

> * what do we want to happen if there already exists a file at `root folder/Builds/Zips/GameName-x.x.x.exe` and/or a folder at `root folder/Builds/GameName-x.x.x`?
- As you mentioned from my comments, I think we can just fail the build. We don't want to overwrite, cause that would potentially lead to a loss of a version of the game, or unneeded building time if the same unchanged version is already built. 
  - We could have a param to the command `-i` for increment the version, where your script will auto increment. I am not opposed to that.

**Comment by EMCain** [comment]
working on this in https://github.com/EMCain/unity-build-tool - may want to move these issues over there

**Comment by EMCain** [comment]
Closing this as I've got the basics down and can create an .exe
